import { ServiceContainer } from "@node-projects/web-component-designer";

// This file will be generated by 'webuiWidgetSync.js' on first start

export function registerNpmWidgets(serviceContainer: ServiceContainer) {
}