import { ServiceContainer } from "@node-projects/web-component-designer";

// This file will be generated by 'ImportmapCreator.js' on NPM installations.

export async function registerDesignerAddons(serviceContainer: ServiceContainer) {
}