/* imports without usage, for polymer bundler or he will not modify import paths */
import './demo/demoData'
import './demo/DemoElement'
import './demo/DemoEnum'
import './demo/DemoStringEnum'
import '@vanillawc/wc-marquee'
import '@doubletrade/lit-datepicker'
import '@material/mwc-button'
import '@material/mwc-checkbox'
import '@material/mwc-circular-progress'
import '@material/mwc-textfield'
import 'wired-elements'
import 'elix/define/elix'
import '@patternfly/pfe-badge/dist/pfe-badge'
import '@patternfly/pfe-button'
import '@patternfly/pfe-codeblock'
import '@spectrum-web-components/button/sp-button.js'
import '../node_modules/@christianliebel/paint/dist/elements/index.js'